# Jekyll configuration

name: Scikit-learn Enhancement Proposals

# url is currently only used only for the RSS feed in feed.xml
#url: https://scotte.github.io/jekyll-clean

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''

# These can be '' to hide the Github or Gitlab nav buttons
#github: 'scotte/jekyll-clean'
gitlab: ''

# Set this to your UA-# value, or '' to disable the block completely
#gaaccount: ''

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['LICENSE']
